options(shiny.maxRequestSize=100*1024^2)
# options(repos = BiocManager::repositories())
# getOption("repos")

function(input, output, session) {
  observeEvent(input$Run_scDEA, {
    # Read in expression dataset
    #write.table(x = Grun.counts.matrix, file = "Grun.counts.matrix.txt", col.names = TRUE, row.names = TRUE, sep = "\t")
    count = read.table(file = input$count$datapath, sep = "\t")
    count = as.matrix(count)
    # write.table(x = Grun.group.information, file = "Grun.group.information.txt", sep = "\t", col.names = FALSE, row.names = FALSE)
    group.information = read.table(file = input$cell_label$datapath, sep = "\t", header = FALSE)
    group.information = as.character(group.information$V1)
    names(group.information) = colnames(count)


    time.used = system.time({
      Results.individual.methods = try(scDEA_individual_methods(raw.count = count, cell.label = group.information,
                                                              is.normalized = input$is.normalized, verbose = input$verbose,
                                                              BPSC = input$BPSC, DEsingle = input$DEsingle, DESeq2 = input$DESeq2, edgeR = input$edgeR,
                                                              MAST = input$MAST, monocle = input$monocle, scDD = input$scDD, Ttest = input$Ttest, Wilcoxon = input$Wilcoxon,
                                                              limma = input$limma, Seurat = input$Seurat, zingeR.edgeR = input$zingeR.edgeR,
                                                              BPSC.coef = input$BPSC.coef, BPSC.normalize = input$BPSC.normalize, BPSC.parallel = input$BPSC.parallel,
                                                              DEsingle.parallel = input$DEsingle.parallel, DEsingle.normalize = input$DEsingle.normalize,
                                                              DESeq2.test = input$DESeq2.test, DESeq2.parallel = input$DESeq2.parallel, DESeq2.beta.prior = input$DESeq2.beta.prior,
                                                              DESeq2.fitType = input$DESeq2.fitType, DESeq2.normalize = input$DESeq2.normalize,
                                                              edgeR.Test = input$edgeR.Test, edgeR.normalize = input$edgeR.normalize,
                                                              limma.method.fit = input$limma.method.fit, limma.trend = input$limma.trend, limma.robust = input$limma.robust, limma.normalize = input$limma.normalize,
                                                              Seurat.normalize = input$Seurat.normalize, Seurat.method = input$Seurat.method,
                                                              MAST.method = input$MAST.method, MAST.normalize = input$MAST.normalize, MAST.parallel = input$MAST.parallel,
                                                              monocle.cores = input$monocle.cores, monocle.normalize = input$monocle.normalize,
                                                              scDD.alpha1 = input$scDD.alpha1, scDD.mu0 = input$scDD.mu0, scDD.s0 = input$scDD.s0, scDD.a0 = input$scDD.a0,
                                                              scDD.b0 = input$scDD.b0, scDD.normalize = input$scDD.normalize, scDD.permutation = input$scDD.permutation,
                                                              Ttest.normalize = input$Ttest.normalize,
                                                              Wilcoxon.normalize = input$Wilcoxon.normalize,
                                                              zingeR.edgeR.normalize = input$zingeR.edgeR.normalize, zingeR.edgeR.maxit.EM = input$zingeR.edgeR.maxit.EM
      ))})

    output$summary1 = renderText("Run individual DE analysis methods is finished")
    output$summary2 = renderText({
      paste("Time used (seconds):", round(as.numeric(time.used[3]),2))
    })


    time.used.scDEA = system.time({
      scDEA.p = try(lancaster.combination(Pvals = Results.individual.methods, weight = input$weight, trimmed = input$trimmed))})
    output$summary3 = renderText("Ensemble the p values generated by individual DE analysis methods")
    output$summary4 = renderText({
      paste("Time used (seconds):", round(as.numeric(time.used.scDEA[3]),2))
    })


    ### Run ensemble process ####
    Seurat.data <- scDEA::data_process(Data = count, group = group.information)
    normalized.data <- as.matrix(assay(Seurat.data, "normcounts"))
    index1 = Seurat.data$label == levels(as.factor(Seurat.data$label))[1]
    index2 = Seurat.data$label == levels(as.factor(Seurat.data$label))[2]
    normalized.data1 <- normalized.data[,index1]
    normalized.data2 <- normalized.data[,index2]

    Basemean = rowMeans(normalized.data1)
    FC <- rowMeans(normalized.data2)/ rowMeans(normalized.data1)
    logFC <- log(FC)

    p.value <-  lancaster.combination(Pvals = Results.individual.methods, weight = input$weight, trimmed = input$trimmed)
    adjust.p.value <- p.adjust(p.value)

    dataframe.scDEA = data.frame(Basemean = Basemean, FC = FC, logFC = logFC,
                                 p.value = p.value, adjust.p.value = adjust.p.value)
    ### Run ensemble process ####

    output$Heatmap_scDEA <- renderPlot({

      object <- Seurat.data
      result <- adjust.p.value
      num.gene <- input$number_genes_show_scDEA

      index <- sort(result)
      features.plot <- names(index)[1:num.gene]

      plot.seurat <- as.Seurat(object, counts = "counts", data = "normcounts")

      plot.seurat <- Seurat::ScaleData(plot.seurat)
      print(Seurat::DoHeatmap(object = plot.seurat, features = features.plot, group.by = 'label'))

      # Visualization(object = Seurat.data, result = adjust.p.value, num.gene = input$number_genes_show_scDEA)
    })



    output$result_scDEA <- DT::renderDataTable({

      DT::datatable(dataframe.scDEA,  extensions = 'Scroller', options = list(
        deferRender = TRUE,
        scrollY = 296,
        scroller = TRUE
      ))

    })

    output$download = downloadHandler(

      filename = function(){ paste(input$dlname, ".", input$fileformat, sep="") },



      content = function(file) {
        if (input$fileformat == "txt"){
            write.table(dataframe.scDEA, file, sep = "\t", quote = FALSE)
        }
        else{
            write.csv(dataframe.scDEA, file,  quote = FALSE)
        }
      }
    )

  })

}
